- src/main/java/com/challenger/fridge/FridgeApplication.java
- src/main/java/com/challenger/fridge/common/ApiStatus.java
- src/main/java/com/challenger/fridge/common/MemberType.java
- src/main/java/com/challenger/fridge/common/StorageMethod.java
- src/main/java/com/challenger/fridge/common/StorageStatus.java
- src/main/java/com/challenger/fridge/domain/Cart.java
- src/main/java/com/challenger/fridge/domain/CartItem.java
- src/main/java/com/challenger/fridge/domain/Category.java
- src/main/java/com/challenger/fridge/domain/Item.java
- src/main/java/com/challenger/fridge/domain/Member.java
- src/main/java/com/challenger/fridge/domain/MemberRefreshToken.java
- src/main/java/com/challenger/fridge/domain/Notice.java
- src/main/java/com/challenger/fridge/domain/Storage.java
- src/main/java/com/challenger/fridge/domain/StorageItem.java
- src/main/java/com/challenger/fridge/dto/ApiResponse.java
- src/main/resources/application.yml
> Feature jjw : 엔티티 설계

- src/main/java/com/challenger/fridge/controller/StorageController.java
- src/main/java/com/challenger/fridge/domain/Member.java
- src/main/java/com/challenger/fridge/domain/Storage.java
- src/main/java/com/challenger/fridge/domain/box/Freeze.java
- src/main/java/com/challenger/fridge/domain/box/Fridge.java
- src/main/java/com/challenger/fridge/domain/box/Room.java
- src/main/java/com/challenger/fridge/domain/box/StorageBox.java
- src/main/java/com/challenger/fridge/dto/storage/request/StorageSaveRequest.java
- src/main/java/com/challenger/fridge/dto/storage/response/CategoryStorageItemResponse.java
- src/main/java/com/challenger/fridge/dto/storage/response/StorageItemResponse.java
- src/main/java/com/challenger/fridge/exception/StorageBoxLimitExceededException.java
- src/main/java/com/challenger/fridge/exception/StorageNameDuplicateException.java
- src/main/java/com/challenger/fridge/handler/ExceptionResponseHandler.java
- src/main/java/com/challenger/fridge/repository/StorageRepository.java
- src/main/java/com/challenger/fridge/service/StorageService.java
- src/test/java/com/challenger/fridge/service/StorageServiceTest.java
보관소 추가 API 완성
보관소 추가 예외발생 관련 테스트 코드 완성
> Feature storage add2

- src/main/java/com/challenger/fridge/controller/SignController.java
domain을 localhost 로 설정하여 로컬 환경에서도 쿠키를 저장할 수 있도록 변경
> Feat: refreshToken 쿠키 설정 변경

- src/main/java/com/challenger/fridge/security/SecurityConfig.java
front 에서 도메인이 달라서 접속 불가능한 현상 발생.
모든 도메인에서 다 접속할 수 있도록 설정하였습니다. 추후에 프론트 서버의 도메인 확정나면 수정 예정입니다.
> Chore: Cors 설정 추가

- src/main/java/com/challenger/fridge/controller/SignController.java
- src/main/java/com/challenger/fridge/security/SecurityConfig.java
front 에서 도메인이 달라서 접속 불가능한 현상 발생.
모든 도메인에서 다 접속할 수 있도록 설정하였습니다. 추후에 프론트 서버의 도메인 확정나면 수정 예정입니다.
> Chore: Cors 설정 추가

- src/main/java/com/challenger/fridge/FridgeApplication.java
- src/main/java/com/challenger/fridge/controller/HomeController.java
root 페이지로 접속할 때 Http Status 가 200인 응답 리턴
> Chore: ssl 인증서 적용을 위한 homecontroller

- src/main/resources/application.yml
> Chore: port 번호 변경

- src/main/resources/application.yml
> Chore: 포트 번호 복구

- src/main/java/com/challenger/fridge/controller/StorageBoxController.java
- src/main/java/com/challenger/fridge/controller/StorageController.java
- src/main/java/com/challenger/fridge/domain/StorageItem.java
- src/main/java/com/challenger/fridge/domain/box/StorageBox.java
- src/main/java/com/challenger/fridge/dto/box/request/StorageBoxUpdateRequest.java
- src/main/java/com/challenger/fridge/dto/box/response/StorageBoxResponse.java
- src/main/java/com/challenger/fridge/dto/item/request/StorageItemUpdateRequest.java
- src/main/java/com/challenger/fridge/service/StorageBoxService.java
- src/main/java/com/challenger/fridge/service/StorageService.java
- src/test/java/com/challenger/fridge/repository/StorageRepositoryTest.java
storageBoxUpdateRequest.getStorageBoxName() == null 로 수정 완료
System.out.print() 제거
> Feature storage update

- src/main/java/com/challenger/fridge/controller/MemberController.java
- src/main/java/com/challenger/fridge/domain/Member.java
- src/main/java/com/challenger/fridge/domain/Storage.java
- src/main/java/com/challenger/fridge/dto/MemberInfoDto.java
- src/main/java/com/challenger/fridge/dto/box/response/StorageBoxNameResponse.java
- src/main/java/com/challenger/fridge/dto/member/MemberInfoRequest.java
- src/main/java/com/challenger/fridge/dto/member/MemberInfoResponse.java
- src/main/java/com/challenger/fridge/repository/MemberRepository.java
- src/main/java/com/challenger/fridge/service/MemberService.java
- src/test/java/com/challenger/fridge/service/MemberServiceTest.java
- 회원 이름, email, 메인 보관소 id, 메인 보관소 이름, 메인보관소 정보(세부보관소 id, 이름) 반환
- 비밀번호와 메인 보관소를 입력하여 변경
> 회원 정보 조회 및 수정 api

- src/main/java/com/challenger/fridge/domain/StorageItem.java
- src/main/java/com/challenger/fridge/dto/box/request/StorageBoxSaveRequest.java
- src/main/java/com/challenger/fridge/dto/item/request/StorageItemRequest.java
- src/main/java/com/challenger/fridge/dto/item/request/StorageItemUpdateRequest.java
- src/main/java/com/challenger/fridge/dto/item/response/StorageItemResponse.java
- src/main/java/com/challenger/fridge/service/StorageService.java
- StorageMethod -->StorageBoxType으로 보낼 수 있도록 변경
- expireDate --> expireationDate 으로 변경
- StorageItemResponse에 purchaseDate도 같이 보낼 수 있도록 변경
> Feature storage reversion2

- src/main/java/com/challenger/fridge/dto/cart/ItemCountRequest.java
> Refactor: 장바구니 상품 수량 조절 API 수정

- src/main/java/com/challenger/fridge/dto/cart/ItemCountRequest.java
- JSON mapping 실패로 인한 기본 생성자 추가
> Refactor: ItemCountRequest 기본 생성자 추가

- src/main/java/com/challenger/fridge/controller/CartController.java
- src/main/java/com/challenger/fridge/domain/CartItem.java
- src/main/java/com/challenger/fridge/service/CartService.java
- src/test/java/com/challenger/fridge/repository/CartRepositoryTest.java
- src/test/java/com/challenger/fridge/service/CartServiceTest.java
- 장바구니 상품별로 사용자가 구매했는지 아닌지 판별하는 isPurchased 필드 를 추가하였습니다.
> Feature: 장바구니 상품 구매 check API 구현 및 테스트 작성

- src/main/java/com/challenger/fridge/security/SecurityConfig.java
- aws ec2 인스턴스에 이상한 요청이 들어와 securityConfig 설정 변경
> Chore: SecurityConfig url과 Http Method 설정 추가 및 정적자원 설정 해제

- src/main/java/com/challenger/fridge/config/RedisService.java
- src/main/java/com/challenger/fridge/controller/MemberController.java
- src/main/java/com/challenger/fridge/controller/SignController.java
- src/main/java/com/challenger/fridge/domain/Member.java
- src/main/java/com/challenger/fridge/security/JwtLogoutHandler.java
- src/main/java/com/challenger/fridge/security/SecurityConfig.java
- src/main/java/com/challenger/fridge/service/FCMService.java
- src/main/java/com/challenger/fridge/service/MemberService.java
- src/main/java/com/challenger/fridge/service/SignService.java
- src/main/resources/application.yml
- 디바이스 토큰이 있을 경우 redis에 토큰 저장 후 알림 설정을 킨다.
- 디바이스 토큰이 없는 경우 알림 설정을 끈다.
- 디바이스 토큰 있는 경우 redis에 저장 후 알림 설정을 킴
- 없는 경우 알림 설정만 끈다
> 로그인/로그아웃 및 알림 수신 변경 API

- src/test/java/com/challenger/fridge/service/NotificationServiceTest.java
> Test: Member 생성 메서드 변경으로 인한 NotificationServiceTest 변경

- .gitignore
- src/main/java/com/challenger/fridge/controller/MemberController.java
- src/main/java/com/challenger/fridge/controller/SignController.java
- src/main/java/com/challenger/fridge/controller/StorageController.java
- src/main/java/com/challenger/fridge/domain/Member.java
- src/main/java/com/challenger/fridge/domain/Storage.java
- src/main/java/com/challenger/fridge/dto/item/response/ItemInfoResponse.java
- src/main/java/com/challenger/fridge/dto/sign/SignInRequest.java
- src/main/java/com/challenger/fridge/dto/storage/request/StorageInfoUpdateRequest.java
- src/main/java/com/challenger/fridge/dto/storage/response/StorageResponse.java
- src/main/java/com/challenger/fridge/repository/CartItemRepository.java
- src/main/java/com/challenger/fridge/repository/MemberRepository.java
- src/main/java/com/challenger/fridge/repository/NotificationRepository.java
- src/main/java/com/challenger/fridge/repository/StorageBoxRepository.java
- src/main/java/com/challenger/fridge/repository/StorageItemRepository.java
- src/main/java/com/challenger/fridge/repository/StorageRepository.java
- src/main/java/com/challenger/fridge/service/MemberService.java
- src/main/java/com/challenger/fridge/service/MemberWithdrawService.java
- src/main/java/com/challenger/fridge/service/SignService.java
- src/main/java/com/challenger/fridge/service/StorageService.java
- src/test/java/com/challenger/fridge/controller/SignControllerTest.java
- src/test/java/com/challenger/fridge/service/MemberServiceTest.java
- src/test/java/com/challenger/fridge/service/SignServiceTest.java
- 보관소 이름 및 보관소 이미지 번호 수정
- deviceToken 필드 추가
> Feature : 회원탈퇴 및 보관소 정보 수정 API 구현

- README.md
> docs : update server read.me

- README.md
> docs : Update erd README.md
